name: Update Adsassin

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * 1-5'

jobs:
  update-adsassin:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget dos2unix

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Shell Script
      run: ./scripts/update-adsassin.sh

    - name: Commit/Push Changes
      run: |
        git config --local user.email "schifferl@users.noreply.github.com"
        git config --local user.name "schifferl"
        git add -A
        git commit -a -m "`date -u`" --allow-empty --quiet
        git push --quiet
